### ISSUE TITLE
grad None

### ISSUE THREAD

**Issue by neosr-project** [nblt/F-SAM#1]
Hi, thanks for your research. If I'm not mistaken, it looks like on `first_step()` a condition [is missing](https://github.com/nblt/F-SAM/blob/main/utils.py#L445). At beginning of training, grad can be None and that causes issue for `clone()`. Adding the condition to it solved the problem for me:
```python
        for group in self.param_groups:
            for p in group["params"]:
                if p.grad is None: continue # this condition
                grad = p.grad.clone()
```

**Comment by nblt** [comment]
Hi, thank you for bringing the issue to our attention. You are right, and we have fixed accordingly.
